import Head from 'next/head'
import Header from './../components/Header';
import Footer from './../components/Footer';
import Nav from '../components/Nav';
import requests from '../utils/requests';
import Movies from '../components/Movies';

export default function Home(props) {
  // console.log(props)
  return (
    <div className="home">
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Movies results = {props.results} />


      {/* <Footer /> */}
    </div>
  )
}

export async function getServerSideProps(context){
  const genre = context.query.genre
  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`).then(res => res.json())
  return {
    props: {
      results: request.results,
    }
  }
}
